 <!-- Start: Footer Basic -->
 <div class="footer-basic" style="padding-bottom: 0;padding-top: 2%; position:fixed; bottom:0;z-index:100;">
        <footer style="width: 100%;">
            <!-- Start: Social Icons -->
            <div class="social" style="width: 100%;padding-bottom: 0;">
            <a href="{{route('mapa',$municipio->id)}}" style="width: 15%;height: none;margin-left: 0%;margin-right: 0;opacity: 1;line-height: 0px;border-top-left-radius: none;border-top-right-radius: 0;border-bottom-right-radius: 0;border-style: none;border-right: 2px solid #000C4F ;"><img src="/assets/img/mapa.svg?h=d408d38985f98701d1e716a42e786cdf" style="width: 80%;margin-bottom: 10%;"><span style="font-size: 9px;">MAPA</span></a>
            <a href="#" style="width: 15%;height: none;margin-left: 0%;margin-right: 0;opacity: 1;line-height: 0px;border-top-left-radius: none;border-top-right-radius: 0;border-bottom-right-radius: 0;border-style: none;border-right: 2px solid #000C4F ;"><img src="/assets/img/comidas.svg?h=b6938b632794e078d60944a42e08cf2e" style="width: 80%;margin-bottom: 10%;"><span style="font-size: 9px;">COMIDAS</span></a>
            <a href="#" style="width: 15%;height: none;margin-left: 0%;margin-right: 0;opacity: 1;line-height: 0px;border-top-left-radius: none;border-top-right-radius: 0;border-bottom-right-radius: 0;border-style: none;border-right: 2px solid #000C4F ;"><img src="/assets/img/hospedaje.svg?h=811d29000a70250b3b70f60a79406116" style="width: 80%;margin-bottom: 10%;"><span style="font-size: 9px;">HOSPEDAJE</span></a>
            <a href="#" style="width: 15%;height: none;margin-left: 0%;margin-right: 0;opacity: 1;line-height: 0px;border-top-left-radius: none;border-top-right-radius: 0;border-bottom-right-radius: 0;border-style: none;border-right: 2px solid #000C4F ;"><img src="/assets/img/ocio.svg?h=595d9f51f91f2526dd288581bdf87a3d" style="width: 80%;margin-bottom: 10%;"><span style="font-size: 9px;">OCIO</span></a>
            <a href="#" style="width: 15%;height: none;margin-left: 0%;margin-right: 0;opacity: 1;line-height: 0px;border-top-left-radius: none;border-top-right-radius: 0;border-bottom-right-radius: 0;border-style: none;border-right: 2px solid #000C4F ;"><img src="/assets/img/bancos.svg?h=b2c6029cac07ada31f0971952002ffe3" style="width: 80%;margin-bottom: 10%;"><span style="font-size: 9px;">BANCOS</span></a>
            <a href="#" style="width: 15%;height: none;margin-left: 0%;margin-right: 0;opacity: 1;line-height: 0px;border-top-left-radius: none;border-top-right-radius: 0;border-bottom-right-radius: 0;border-style: none;border-right: 2px none var(--dark) ;"><img src="/assets/img/artesanias.svg?h=5b8e6ad8fb7f268316922e9795cc63a2" style="width: 80%;margin-bottom: 10%;"><span style="font-size: 9px;margin-top: 0;">ARTESANIAS</span></a>
            </div><!-- End: Social Icons -->
        </footer>
    </div><!-- End: Footer Basic -->